//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MegaCasting.DBLib
{
    using System;
    using System.Collections.ObjectModel;
    
    public partial class PackPaid
    {
        public long Identifier { get; set; }
        public long IdClient { get; set; }
        public Nullable<long> IdPack { get; set; }
        public Nullable<int> NumberOffers { get; set; }
        public Nullable<int> NumberDays { get; set; }
        public System.DateTime DatePaiment { get; set; }
    
        public virtual Client Client { get; set; }
        public virtual Pack Pack { get; set; }
    }
}
