//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MegaCasting.DBLib
{
    using System;
    using System.Collections.ObjectModel;
    
    public partial class Post
    {
        public long Identifier { get; set; }
        public System.DateTime DatePost { get; set; }
        public string Letter { get; set; }
        public string CV { get; set; }
        public long IdOffer { get; set; }
        public long IdWebUser { get; set; }
    
        public virtual Offer Offer { get; set; }
        public virtual WebUser WebUser { get; set; }
    }
}
